<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
</head>
<body>
    <form method="post" action="/enter">
        <input type="text" name="name" placeholder="name"/>
        <input type="text" name="phone_number" placeholder="number"/>
        <button type="submit"> Add</button>
    </form>

</body>